---
name: CD

on:
  push:
  pull_request:

jobs:
  publish:
    name: Publishing for ${{ matrix.job.os  }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        job:
          - os: macos-latest
          - os: ubuntu-latest
          - os: ubuntu-24.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Cargo build
        run: |
          cargo build --release
      - name: Packaging final binary
        shell: bash
        run: |
          cd target/release

          BINARY_NAME=nixpkgs-context
          REFNAME=${{  github.ref_name }}
          # Avoid issues with refnames that have slashes, like `nixpkgs-context-dependabot/cargo/h2-0.3.26`
          REFNAME=${REFNAME//\//-}
          OSNAME=$(uname | tr 'A-Z' 'a-z')
          ARCH=$(uname -m)

          RELEASE_NAME=${BINARY_NAME}-${REFNAME}-${OSNAME}-${ARCH}
          tar czvf "$RELEASE_NAME.tar.gz" "$BINARY_NAME"
          shasum -a 256 $RELEASE_NAME.tar.gz > $RELEASE_NAME.sha256

      - name: Releasing assets
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v3
        with:
          files: |
            target/release/nixpkgs-context-*.tar.gz
            target/release/nixpkgs-context-*.sha256

  publish-cargo:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Publishing to Cargo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: cargo publish --token "${{ secrets.NIXPKGS_CONTEXT_CARGO_PUBLISH_TOKEN }}"
